apiVersion: batch/v1
kind: Job
metadata:
  name: video-processor-job
spec:
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      runtimeClassName: nvidia
      containers:
      - name: video-processor
        image: ghcr.io/twoabove/k3s-video-processing-worker:main
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1  # Request 1 GPU
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        envFrom:
        - secretRef:
            name: db-credentials
      restartPolicy: OnFailure
